@authorization= Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1pcnpheCIsImlhdCI6MTY1MjU0NDQxMCwiZXhwIjoxNjUyNTQ4MDEwfQ.x7rCOlbscObUD06IfMhqfHtYDWnWnyDnMy9rXQVSfrc

@local=http://localhost:3000

@remote=https://nesttaskappmirzaop.herokuapp.com
@base_url ={{remote}}
###
GET {{base_url}}/tasks/
Authorization: {{authorization}}


###
POST {{base_url}}/tasks/
content-type: application/json
Authorization: {{authorization}}

{
  "title": "Task no 3",
  "description": "this is description 3"
}

###
DELETE  {{base_url}}/tasks/2
Authorization: {{authorization}}

###GET TASK BY ID
GET {{base_url}}/tasks/2
Authorization: {{authorization}}

###
PATCH {{base_url}}/tasks/5/status
content-type: application/json
Authorization: {{authorization}}

{
  "status": "DONE"
}

###
GET {{base_url}}/tasks?status=OPEN&search=this
Authorization: {{authorization}}

###
POST {{base_url}}/auth/signup/
content-type: application/json


{
  "username":"mirzax2",
  "password":"12345$ABCx"
}

###
POST {{base_url}}/auth/signin/
content-type: application/json

 
{
  "username":"mirzax2",
  "password":"12345$ABCx"
}


###
POST {{base_url}}/auth/test/
Content-Type: application/json
Authorization: {{authorization}}

###
GET {{base_url}}/